user:
  nickname:
    length:
      maximum: 20

site:
  name:
    length:
      maximum: 20
  url:
    length:
      maximum: 2083
  comment:
    length:
      maximum: 140
  screenshot:
    length:
      maximum: <%= 1024 * 1024 * 5 %>

skill:
  name:
    length:
      maximum: 10

reaction:
  name:
    length:
      maximum: 10

per_page: 10
